/**
 * Version Parser
 *
 * Parses version strings from generated context files.
 * Supports multiple version marker formats used by k0ntext.
 */

/**
 * Version marker patterns found in generated files
 */
const VERSION_PATTERNS = [
  // Format: *Generated by k0ntext v3.3.1*
  /\*Generated by k0ntext v(\d+\.\d+\.\d+[^*)]*)\*/,
  // Format: > **Version:** 3.3.1
  /\*\*Version:\*\*\s*(\d+\.\d+\.\d+[^,\s]*)/,
  // Format: > Version: 3.3.1
  /Version:\s*(\d+\.\d+\.\d+[^,\s]*)/,
  // Format: "generator_version": "3.3.1"
  /"generator_version":\s*"(\d+\.\d+\.\d+[^"]*)"/,
  // Format: <!-- Version: 3.3.1 -->
  /<!--\s*Version:\s*(\d+\.\d+\.\d+[^-\s]*)/,
] as const;

/**
 * Parse version from file content
 *
 * @param content - File content to search for version
 * @returns Version string if found, null otherwise
 */
export function parseVersion(content: string): string | null {
  if (!content || typeof content !== 'string') {
    return null;
  }

  for (const pattern of VERSION_PATTERNS) {
    const match = content.match(pattern);
    if (match && match[1]) {
      return match[1].trim();
    }
  }

  return null;
}

/**
 * Check if content has any version marker
 *
 * @param content - File content to check
 * @returns True if any version pattern is found
 */
export function hasVersionMarker(content: string): boolean {
  if (!content || typeof content !== 'string') {
    return false;
  }

  return VERSION_PATTERNS.some(pattern => pattern.test(content));
}

/**
 * Extract version from first N lines of a file
 * Useful for quick checks without reading entire file
 *
 * @param content - File content (or first N lines)
 * @param lines - Number of lines to check (default: 50)
 * @returns Version string if found, null otherwise
 */
export function parseVersionFromHeader(content: string, lines = 50): string | null {
  if (!content || typeof content !== 'string') {
    return null;
  }

  // Only check first N lines
  const linesToCheck = content.split('\n').slice(0, lines).join('\n');
  return parseVersion(linesToCheck);
}

/**
 * Get all version markers found in content
 * Useful for debugging or validation
 *
 * @param content - File content to search
 * @returns Array of found version strings
 */
export function findAllVersions(content: string): string[] {
  if (!content || typeof content !== 'string') {
    return [];
  }

  const versions: string[] = [];

  for (const pattern of VERSION_PATTERNS) {
    const matches = content.matchAll(new RegExp(pattern, 'g'));
    for (const match of matches) {
      if (match[1]) {
        versions.push(match[1].trim());
      }
    }
  }

  return [...new Set(versions)]; // Deduplicate
}
