/**
 * AI Context Engineering - File Installer
 *
 * Handles copying template files and creating directory structure.
 * Supports multiple AI tools: Claude, Copilot, Cline, Antigravity.
 */

const fs = require('fs');
const path = require('path');

/**
 * Context directory name (universal)
 */
const AI_CONTEXT_DIR = '.ai-context';

/**
 * Root context file name (universal)
 */
const AI_CONTEXT_FILE = 'AI_CONTEXT.md';

/**
 * Directory structure for .ai-context/
 */
const DIRECTORY_STRUCTURE = [
  'agents',
  'automation',
  'automation/generators',
  'automation/hooks',
  'commands',
  'config',
  'config/environments',
  'context',
  'context/workflows',
  'context/.meta',
  'federation',
  'federation/registry',
  'indexes',
  'indexes/agents',
  'indexes/code',
  'indexes/routing',
  'indexes/search',
  'indexes/workflows',
  'knowledge',
  'knowledge/sessions',
  'knowledge/shared',
  'knowledge/shared/decisions',
  'knowledge/shared/patterns',
  'plans',
  'plans/active',
  'plans/completed',
  'research',
  'research/active',
  'research/completed',
  'schemas',
  'session',
  'session/current',
  'session/history',
  'session/checkpoints',
  'standards',
  'sync',
  'team',
  'ci-templates',
  'ci-templates/github-actions',
  'tools',
  'tools/bin',
  'tools/lib',
];

/**
 * Create the .ai-context directory structure
 */
async function createDirectoryStructure(targetDir, config = {}) {
  const contextDir = path.join(targetDir, AI_CONTEXT_DIR);

  // Create main .ai-context directory
  if (!fs.existsSync(contextDir)) {
    fs.mkdirSync(contextDir, { recursive: true });
  }

  let dirsCreated = 0;

  // Filter directories based on features
  let dirsToCreate = [...DIRECTORY_STRUCTURE];

  if (!config.features?.ci) {
    dirsToCreate = dirsToCreate.filter(d => !d.startsWith('ci-templates'));
  }
  if (!config.features?.team) {
    dirsToCreate = dirsToCreate.filter(d => !d.startsWith('team') && !d.includes('knowledge'));
  }
  if (!config.features?.analytics) {
    dirsToCreate = dirsToCreate.filter(d => !d.startsWith('analytics'));
  }
  if (!config.monorepo) {
    // Keep federation directory but it won't be heavily populated
  }

  // Create each directory
  for (const dir of dirsToCreate) {
    const fullPath = path.join(contextDir, dir);
    if (!fs.existsSync(fullPath)) {
      fs.mkdirSync(fullPath, { recursive: true });
      dirsCreated++;
    }
  }

  return dirsCreated;
}

/**
 * Copy template files from the bundled templates
 */
async function copyTemplates(targetDir, config = {}) {
  const contextDir = path.join(targetDir, AI_CONTEXT_DIR);
  const templatesDir = path.join(__dirname, '..', 'templates', 'base');

  let filesCopied = 0;

  // Check if templates exist
  if (!fs.existsSync(templatesDir)) {
    // If no bundled templates, create minimal files
    filesCopied = await createMinimalFiles(contextDir, config);
    return filesCopied;
  }

  // Copy all files from templates
  filesCopied = await copyDirectory(templatesDir, contextDir);

  return filesCopied;
}

/**
 * Recursively copy a directory
 */
async function copyDirectory(src, dest) {
  let count = 0;

  if (!fs.existsSync(src)) {
    return count;
  }

  const entries = fs.readdirSync(src, { withFileTypes: true });

  for (const entry of entries) {
    const srcPath = path.join(src, entry.name);
    const destPath = path.join(dest, entry.name);

    if (entry.isDirectory()) {
      if (!fs.existsSync(destPath)) {
        fs.mkdirSync(destPath, { recursive: true });
      }
      count += await copyDirectory(srcPath, destPath);
    } else {
      // Copy file
      fs.copyFileSync(srcPath, destPath);
      count++;
    }
  }

  return count;
}

/**
 * Create minimal files when no templates are bundled
 */
async function createMinimalFiles(contextDir, config = {}) {
  let count = 0;

  // README.md
  const readmeContent = `# .ai-context Configuration - ${config.projectName || 'Project'}

This directory contains the AI Context Engineering system.

## Supported AI Tools

- **Claude Code** - Full context in AI_CONTEXT.md
- **GitHub Copilot** - .github/copilot-instructions.md
- **Cline** - .clinerules
- **Antigravity** - .agent/ directory

## Quick Start

1. Load workflow index: Read \`.ai-context/context/WORKFLOW_INDEX.md\`
2. Use RPI workflow: /rpi-research → /rpi-plan → /rpi-implement
3. Validate changes: /verify-docs-current

## Configuration

- **Agents**: ${config.features?.agents ? '6 specialized agents' : 'disabled'}
- **Commands**: ${config.features?.rpi ? 'RPI workflow + validation' : 'basic'}
- **Context Budget**: 200k tokens max, target <40%

*Generated by create-ai-context v2.0*
`;
  fs.writeFileSync(path.join(contextDir, 'README.md'), readmeContent);
  count++;

  // settings.json
  const settingsContent = {
    '$schema': './schemas/settings.schema.json',
    version: '2.0.0',
    project: {
      name: config.projectName || 'my-project',
      status: 'development'
    },
    context: {
      maxTokens: 200000,
      targetUtilization: 0.4
    },
    aiTools: {
      claude: { enabled: true },
      copilot: { enabled: true },
      cline: { enabled: true },
      antigravity: { enabled: false }
    },
    validation: {
      lineAccuracyThreshold: 60,
      onCommit: true
    }
  };
  fs.writeFileSync(
    path.join(contextDir, 'settings.json'),
    JSON.stringify(settingsContent, null, 2)
  );
  count++;

  // WORKFLOW_INDEX.md
  const workflowIndexContent = `# Workflow Index

## Primary Workflows

| Workflow | Entry Point | Description |
|----------|-------------|-------------|
| *To be discovered* | - | Run static analysis or AI to populate |

## Quick Reference

- Use \`/rpi-research\` to discover workflows
- Use \`@context-engineer\` for Claude-enhanced setup

*Run analysis to populate this index.*
`;
  fs.writeFileSync(
    path.join(contextDir, 'context', 'WORKFLOW_INDEX.md'),
    workflowIndexContent
  );
  count++;

  // RPI_WORKFLOW_PLAN.md
  const rpiContent = `# RPI (Research, Plan, Implement) Workflow

## Phase 1: RESEARCH (/rpi-research)
- Explore codebase using parallel agents
- Output: Research document in \`.ai-context/research/active/\`

## Phase 2: PLAN (/rpi-plan)
- Create implementation blueprint with file:line precision
- Output: Plan document in \`.ai-context/plans/active/\`

## Phase 3: IMPLEMENT (/rpi-implement)
- Execute with atomic changes
- ONE CHANGE → ONE TEST → ONE COMMIT

## Context Budget
- Research: 25-30%
- Plan: 20-25%
- Implement: 30-40%
`;
  fs.writeFileSync(path.join(contextDir, 'RPI_WORKFLOW_PLAN.md'), rpiContent);
  count++;

  // Create placeholder files for research and plans
  const researchTemplate = `# Research Template

Use this template for RPI Research phase.

## Objective
[What you're researching]

## Files Explored
| File | Lines | Findings |
|------|-------|----------|

## Summary
[150 words max]
`;
  fs.writeFileSync(
    path.join(contextDir, 'research', 'RESEARCH_TEMPLATE.md'),
    researchTemplate
  );
  count++;

  const planTemplate = `# Plan Template

Use this template for RPI Plan phase.

## Research Summary
[From Phase 1]

## Files to Modify
| File | Lines | Change | Risk |
|------|-------|--------|------|

## Steps
1. Step 1
2. Step 2

## Rollback Plan
- Revert: \`git revert HEAD\`
`;
  fs.writeFileSync(
    path.join(contextDir, 'plans', 'PLAN_TEMPLATE.md'),
    planTemplate
  );
  count++;

  return count;
}

/**
 * Create AI_CONTEXT.md at project root
 */
async function createAiContextMd(targetDir, config = {}, techStack = {}) {
  const aiContextPath = path.join(targetDir, AI_CONTEXT_FILE);

  // Check for template
  const templatePath = path.join(__dirname, '..', 'templates', 'AI_CONTEXT.md.template');

  let content;

  if (fs.existsSync(templatePath)) {
    content = fs.readFileSync(templatePath, 'utf8');
  } else {
    // Create minimal AI_CONTEXT.md
    content = `# AI_CONTEXT.md - ${config.projectName || 'Project'}

This file provides guidance to AI coding assistants when working with this repository.

---

## Project Identity

**Platform:** ${config.projectName || 'Project'} application
**Tech Stack:** ${techStack.summary || techStack.stack || 'Not detected'}
**Status:** Development

---

## Essential Commands

### Development
\`\`\`bash
${techStack.commands?.install || 'npm install'}
${techStack.commands?.dev || 'npm run dev'}
\`\`\`

### Testing
\`\`\`bash
${techStack.commands?.test || 'npm test'}
\`\`\`

---

## Navigation Rules

### High-Level Task
1. Start: [.ai-context/context/WORKFLOW_INDEX.md](./.ai-context/context/WORKFLOW_INDEX.md)
2. Load relevant workflow
3. Implement with context

### Feature Development
1. /rpi-research - Explore codebase
2. /rpi-plan - Create blueprint
3. /rpi-implement - Execute with tests

---

## Documentation System

**Navigation:** 3-level chain (AI_CONTEXT.md → Category → Domain → Detail)
**Validation:** Run /verify-docs-current after modifications
**RPI Workflow:** /rpi-research → /rpi-plan → /rpi-implement

See: [.ai-context/RPI_WORKFLOW_PLAN.md](./.ai-context/RPI_WORKFLOW_PLAN.md)

---

## AI Tools Configuration

This context is optimized for:
- **Claude Code** - Full context reading
- **GitHub Copilot** - See \`.github/copilot-instructions.md\`
- **Cline** - See \`.clinerules\`
- **Antigravity** - See \`.agent/\` directory

---

*Generated by create-ai-context v2.0*
`;
  }

  fs.writeFileSync(aiContextPath, content);
}

/**
 * Legacy alias for backward compatibility
 */
const createClaudeMd = createAiContextMd;

module.exports = {
  createDirectoryStructure,
  copyTemplates,
  createAiContextMd,
  createClaudeMd, // Legacy alias
  DIRECTORY_STRUCTURE,
  AI_CONTEXT_DIR,
  AI_CONTEXT_FILE,
};
