/**
 * Unit tests for Template Coordination Module
 */

const {
  getToolCoordinationHeader,
  getToolCoordinationFooter,
  isManagedFile,
  getUniversalContextReference,
  formatCoordinationMessage
} = require('../../lib/template-coordination');

const fs = require('fs');
const path = require('path');
const os = require('os');

// Helper to create temp files
const createTempFile = (content = '') => {
  const tempDir = fs.mkdtempSync(path.join(os.tmpdir(), 'test-coordination-'));
  const tempFile = path.join(tempDir, 'test-file.md');
  fs.writeFileSync(tempFile, content);
  return tempFile;
};

// Helper to cleanup temp files
const cleanupTempFile = (tempFile) => {
  if (fs.existsSync(tempFile)) {
    const tempDir = path.dirname(tempFile);
    fs.unlinkSync(tempFile);
    fs.rmSync(tempDir, { recursive: true, force: true });
  }
};

describe('Template Coordination Module', () => {
  describe('getToolCoordinationHeader', () => {
    test('returns header for claude tool', () => {
      const header = getToolCoordinationHeader('claude', '2.3.0');
      expect(header).toContain('CLAUDE CODE CONTEXT');
      expect(header).toContain('Managed by create-ai-context v2.3.0');
      expect(header).toContain('.ai-context/');
    });

    test('returns header for copilot tool', () => {
      const header = getToolCoordinationHeader('copilot', '2.3.0');
      expect(header).toContain('GITHUB COPILOT INSTRUCTIONS');
      expect(header).toContain('Managed by create-ai-context');
    });

    test('returns header for cline tool', () => {
      const header = getToolCoordinationHeader('cline', '2.3.0');
      expect(header).toContain('CLINE RULES');
      expect(header).toContain('Managed by create-ai-context');
    });

    test('returns header for antigravity tool', () => {
      const header = getToolCoordinationHeader('antigravity', '2.3.0');
      expect(header).toContain('ANTIGRAVITY CONTEXT');
      expect(header).toContain('Managed by create-ai-context');
    });

    test('returns empty string for unknown tool', () => {
      const header = getToolCoordinationHeader('unknown', '2.3.0');
      expect(header).toBe('');
    });

    test('uses default version when not provided', () => {
      const header = getToolCoordinationHeader('claude');
      expect(header).toContain('v2.3.0');
    });
  });

  describe('getToolCoordinationFooter', () => {
    test('returns footer with tool-specific regenerate command', () => {
      const footer = getToolCoordinationFooter('copilot');
      expect(footer).toContain('npx create-ai-context generate --ai copilot');
      expect(footer).toContain('.ai-context/');
      expect(footer).toContain('AI_CONTEXT.md');
      expect(footer).toContain('copilot-instructions.md');
      expect(footer).toContain('clinerules');
      expect(footer).toContain('.agent/');
    });

    test('includes all tool references', () => {
      const footer = getToolCoordinationFooter('claude');
      expect(footer).toContain('Claude Code: `AI_CONTEXT.md`');
      expect(footer).toContain('GitHub Copilot: `.github/copilot-instructions.md`');
      expect(footer).toContain('Cline: `.clinerules`');
      expect(footer).toContain('Antigravity: `.agent/`');
    });
  });

  describe('isManagedFile', () => {
    let tempFile;

    afterEach(() => {
      if (tempFile) {
        cleanupTempFile(tempFile);
        tempFile = null;
      }
    });

    test('returns false for non-existent file', () => {
      const result = isManagedFile('/nonexistent/file.md');
      expect(result).toBe(false);
    });

    test('returns true for file with "Managed by create-ai-context"', () => {
      tempFile = createTempFile('<!-- Managed by create-ai-context -->\n# Content');
      expect(isManagedFile(tempFile)).toBe(true);
    });

    test('returns true for file with "CREATE-AI-CONTEXT"', () => {
      tempFile = createTempFile('<!-- CREATE-AI-CONTEXT -->\n# Content');
      expect(isManagedFile(tempFile)).toBe(true);
    });

    test('returns true for file with "Auto-generated by AI Context Engineering"', () => {
      tempFile = createTempFile('<!-- Auto-generated by AI Context Engineering -->\n# Content');
      expect(isManagedFile(tempFile)).toBe(true);
    });

    test('returns false for custom file without markers', () => {
      tempFile = createTempFile('# Custom Content\nNo markers here.');
      expect(isManagedFile(tempFile)).toBe(false);
    });
  });

  describe('getUniversalContextReference', () => {
    const ref = getUniversalContextReference();

    test('returns object with directory info', () => {
      expect(ref.directory).toBe('.ai-context');
      expect(ref.description).toBeTruthy();
    });

    test('returns subdirectory paths', () => {
      expect(ref.subdirectories.agents).toBe('.ai-context/agents/');
      expect(ref.subdirectories.commands).toBe('.ai-context/commands/');
      expect(ref.subdirectories.context).toBe('.ai-context/context/');
      expect(ref.subdirectories.custom).toBe('.ai-context/custom/');
    });

    test('returns main file reference', () => {
      expect(ref.mainFile).toBe('AI_CONTEXT.md');
      expect(ref.workflowIndex).toBe('.ai-context/context/WORKFLOW_INDEX.md');
    });
  });

  describe('formatCoordinationMessage', () => {
    test('returns message for claude tool', () => {
      const msg = formatCoordinationMessage('claude');
      expect(msg).toContain('Claude Code');
      expect(msg).toContain('.ai-context/');
    });

    test('returns message for copilot tool', () => {
      const msg = formatCoordinationMessage('copilot');
      expect(msg).toContain('Copilot');
      expect(msg).toContain('generated');
    });

    test('returns message for cline tool', () => {
      const msg = formatCoordinationMessage('cline');
      expect(msg).toContain('Cline');
    });

    test('returns message for antigravity tool', () => {
      const msg = formatCoordinationMessage('antigravity');
      expect(msg).toContain('Antigravity');
    });
  });
});
